# Activity 6: Using a Sequential Model

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [10]:
# We use sequential models when we want a stack of layers,
# each with one input and one output tensor(array)

model = keras.Sequential([
    layers.Dense(2, activation = 'relu', name = "layer1"),
    layers.Dense(3, activation = 'relu', name = "layer2"),
    layers.Dense(4, name = "layer3")
])

x = tf.ones((3,3))
y1 = model(x)

# this is equivalent to:
# predictions will be different

layer1 = layers.Dense(2, activation = 'relu', name = "layero")
layer2 = layers.Dense(3, activation = 'relu', name = "layert")
layer3 = layers.Dense(4, name = "layersth")

y2 = layer3(layer2(layer1(x)))

print("Y: {} \nY: {}".format(y1, y2))

Y: [[ 0.13331424 -0.07491567 -0.22663169 -0.15190166]
 [ 0.13331424 -0.07491567 -0.22663169 -0.15190166]
 [ 0.13331424 -0.07491567 -0.22663169 -0.15190166]] 
Y: [[ 0.3562271   0.0884752  -0.11548308 -0.09347005]
 [ 0.3562271   0.0884752  -0.11548308 -0.09347005]
 [ 0.3562271   0.0884752  -0.11548308 -0.09347005]]


In [17]:

# we can also add layers with the .add() method
model = keras.Sequential()
model.add(layers.Dense(2, activation = 'relu', name = "layer1"))
model.add(layers.Dense(3, activation = 'relu', name = "layer2"))
model.add(layers.Dense(4, name = "layer3"))

# get layers: 
print(model.layers)

# pop off the last layer. Model layers behave like a list. 
model.pop()
print("\n\n" + str(model.layers))

# get weights too. Initialized empty
model.layers[0].weights

[<tensorflow.python.keras.layers.core.Dense object at 0x1033c63c8>, <tensorflow.python.keras.layers.core.Dense object at 0x134141518>, <tensorflow.python.keras.layers.core.Dense object at 0x134137080>]


[<tensorflow.python.keras.layers.core.Dense object at 0x1033c63c8>, <tensorflow.python.keras.layers.core.Dense object at 0x134141518>]


[]

In [20]:
# change weights from test input
x = tf.ones((1,4))
y = model.layers[0](x)
model.layers[0].weights

[<tf.Variable 'layer1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.1193912 , -0.1624546 ],
        [-0.07678819,  0.85056305],
        [ 0.20572376, -0.5221989 ],
        [ 0.1638124 ,  0.79302096]], dtype=float32)>,
 <tf.Variable 'layer1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [26]:
# model.weights # doesn't work, no weights on every layer but the first yet. 

y = model(x) # give it a test input

# try again
model.weights

# only two layers since we popped the last layer off. 
model.add(layers.Dense(4))

len(model.weights)

model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (1, 2)                    10        
_________________________________________________________________
layer2 (Dense)               (1, 3)                    9         
_________________________________________________________________
dense (Dense)                (1, 4)                    16        
_________________________________________________________________
dense_1 (Dense)              (1, 4)                    20        
_________________________________________________________________
dense_2 (Dense)              (1, 4)                    20        
_________________________________________________________________
dense_3 (Dense)              (1, 4)                    20        
Total params: 95
Trainable params: 95
Non-trainable params: 0
_________________________________________________________

In [27]:
# new model now 

model = keras.Sequential()

model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, activation = "relu"))

# model needs to know its input shape before it can give you a summary
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [28]:
# can also just do this
model = keras.Sequential()

model.add(layers.Dense(2, activation = "relu", input_shape = (4,)))

# predefining input shape intializes some weights
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [29]:
# add layers -> summary -> add layers is a common workflow
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


In [30]:
# again
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 38, 38, 32)        9248      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 36, 36, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 10, 10, 32)      

In [31]:
model.add(layers.GlobalMaxPooling2D())

model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 38, 38, 32)        9248      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 36, 36, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 10, 10, 32)      

In [32]:
# add classification layer at end
model.add(layers.Dense(10))

In [35]:
# next steps:
# train
# serialize and save to disk
# speed up with multi-GPU training

# we can extract features from intermediate layers 
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    # just get the outputs from a specific named layer 
    # see what they are 
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)

# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
print(features)

tf.Tensor(
[[[[0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   ...
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]]

  [[0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   ...
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]
   [0.14073473 0.1845641  0.         ... 0.15254222 0.01145196
    0.        ]]

  [[0.14073473 0.184564

This tutorial was taken from TensorFlow Core:
https://www.tensorflow.org/guide/keras/sequential_model